Repository ljlm0402/typescript-express-starter, pull requests merged in 2022-07, with the labels that each got.

#173 🛠 Refactoring Code
  README.md
  lib/default/src/services/auth.service.ts
  lib/default/src/services/users.service.ts
  lib/graphql/src/repositories/auth.repository.ts
  lib/graphql/src/repositories/users.repository.ts
  lib/knex/src/services/auth.service.ts
  lib/knex/src/services/users.service.ts
  lib/mikro-orm/src/services/auth.service.ts
  lib/mikro-orm/src/services/users.service.ts
  lib/mongoose/src/services/auth.service.ts
  lib/mongoose/src/services/users.service.ts
  lib/prisma/src/services/auth.service.ts
  lib/prisma/src/services/users.service.ts
  lib/routing-controllers/src/services/auth.service.ts
  lib/routing-controllers/src/services/users.service.ts
  lib/sequelize/src/services/auth.service.ts
  lib/sequelize/src/services/users.service.ts
  lib/typegoose/src/services/auth.service.ts
  lib/typegoose/src/services/users.service.ts
  lib/typeorm/src/services/auth.service.ts
  lib/typeorm/src/services/users.service.ts
Labels: Fix 👉

#175 Update package.json and remove useFindAndModify is not supported ( mongoose )
  README.md
  lib/mongoose/src/databases/index.ts
Labels: Fix 👉, Develop 👉

#177 🌼 Update Version - v9.2.0
  README.kr.md
  lib/default/jest.config.js
  lib/default/package.json
  lib/default/src/services/auth.service.ts
  lib/default/src/services/users.service.ts
  lib/graphql/jest.config.js
  lib/graphql/package.json
  lib/graphql/src/repositories/auth.repository.ts
  lib/graphql/src/repositories/users.repository.ts
  lib/knex/jest.config.js
  lib/knex/knexfile.ts
  lib/knex/package.json
  lib/knex/src/databases/migrations/20210713110926_initial.ts
  lib/knex/src/services/auth.service.ts
  lib/knex/src/services/users.service.ts
  lib/mikro-orm/package.json
  lib/mikro-orm/src/services/auth.service.ts
  lib/mikro-orm/src/services/users.service.ts
  lib/mongoose/jest.config.js
  lib/mongoose/package.json
  lib/mongoose/src/services/auth.service.ts
  lib/mongoose/src/services/users.service.ts
  lib/prisma/jest.config.js
  lib/prisma/package.json
  lib/prisma/src/services/auth.service.ts
  lib/prisma/src/services/users.service.ts
  lib/routing-controllers/jest.config.js
  lib/routing-controllers/package.json
  lib/routing-controllers/src/services/auth.service.ts
  lib/routing-controllers/src/services/users.service.ts
  lib/sequelize/jest.config.js
  lib/sequelize/package.json
  lib/sequelize/src/services/auth.service.ts
  lib/sequelize/src/services/users.service.ts
  lib/starter.js
  lib/typegoose/jest.config.js
  lib/typegoose/package.json
  lib/typegoose/src/middlewares/validation.middleware.ts
  lib/typegoose/src/services/auth.service.ts
  lib/typegoose/src/services/users.service.ts
  lib/typeorm/jest.config.js
  lib/typeorm/package.json
  lib/typeorm/src/databases/index.ts
  lib/typeorm/src/services/auth.service.ts
  lib/typeorm/src/services/users.service.ts
  lib/typeorm/src/tests/auth.test.ts
  lib/typeorm/src/tests/users.test.ts
  package.json
Labels: 🐞 Bug, Fix 👉, Develop 👉
